# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='company',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='business_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='company_id',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='company_id_set', to='wdapp.Company'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_driver_id_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(choices=[(1, 'fuel'), (2, 'nondurable manfacturer'), (3, 'tech'), (4, 'retail'), (5, 'wholesale trade'), (6, 'state_military_federal'), (7, 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businessorder',
            name='hazmat_class',
            field=models.IntegerField(choices=[(1, 'Non-hazard'), (2, 'Explosive'), (3, 'Gases'), (4, 'Flammable Liquid'), (5, 'Combustible Liquid'), (6, 'Flammable Solid'), (7, 'Spontanaeously Combustible'), (8, 'Dangerous When Wet'), (10, 'Oxidizer and Organic Peroxide'), (11, 'Poison (Toxic) and Poison Inhalation Hazard'), (12, 'Radioactive'), (models.TextField(blank=True), 'Miscellaneous, and the general Dangerous placard')], null=True),
        ),
        migrations.AlterField(
            model_name='businessorder',
            name='order_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessorder',
            name='service_type',
            field=models.IntegerField(choices=[(0, 'pickup'), (1, 'delivery')], null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='trucking_specilization',
            field=models.CharField(choices=[('Fuel', 'fuel'), ('Manfacturer', 'nondurable manfacturer'), ('Technology', 'tech'), ('Retail', 'retail'), ('Wholesale', 'wholesale trade'), ('Goverment', 'Goverment'), ('Other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.CharField(choices=[('A', 'class a'), ('B', 'class b'), ('C', 'class c')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='other_license',
            field=models.CharField(choices=[('A', 'class a'), ('B', 'class b'), ('C', 'class c')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='other_license_2',
            field=models.CharField(choices=[('A', 'class a'), ('B', 'class b'), ('C', 'class c')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='wage_plan',
            field=models.CharField(choices=[('Hourly', 'hourly'), ('Miles', 'miles')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='beginnning_weather_conditions',
            field=models.CharField(choices=[(1, 'normal'), (2, 'cloudy'), (3, 'rain'), (4, 'snow'), (5, 'hazardous'), (6, 'extremly hazardous')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ending_weather_conditions',
            field=models.CharField(choices=[(1, 'normal'), (2, 'cloudy'), (3, 'rain'), (4, 'snow'), (5, 'hazardous'), (6, 'extremly hazardous')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_card_usage',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='midway_weather_conditions',
            field=models.CharField(choices=[(1, 'normal'), (2, 'cloudy'), (3, 'rain'), (4, 'snow'), (5, 'hazardous'), (6, 'extremly hazardous')], max_length=50, null=True),
        ),
    ]
