# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0003_auto_20181205_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessorder',
            old_name='business_id',
            new_name='business',
        ),
        migrations.RemoveField(
            model_name='businessorder',
            name='weight',
        ),
    ]
