# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-15 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0008_driver_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('Receipt_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='meal',
            new_name='cargo',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='wdapp.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_logo/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
