# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0009_auto_20181115_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('point_of_contact', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('business_phone_number', models.IntegerField(null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.TextField(null=True)),
                ('industry', models.IntegerField(choices=[(1, 'fuel'), (2, 'nondurable manfacturer'), (3, 'tech'), (4, 'retail'), (5, 'wholesale trade'), (6, 'state_military_federal'), (7, 'other')])),
                ('time_open', models.TimeField(null=True)),
                ('time_closed', models.TimeField(null=True)),
                ('availability', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('other_details', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MISC', models.TextField(blank=True)),
                ('order_id', models.IntegerField(max_length=7, null=True)),
                ('point_of_contact', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('distance_from_company_facility', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_delivery_day', models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], default=1)),
                ('preferred_delivery_date', models.DateTimeField()),
                ('business_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Business')),
            ],
        ),
        migrations.CreateModel(
            name='CargoManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_id', models.IntegerField(max_length=7, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_updated', models.DateTimeField(auto_now=True)),
                ('approximate_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.BusinessOrder')),
                ('distance_from_company_facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.BusinessOrder')),
            ],
        ),
        migrations.CreateModel(
            name='DriverExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_number', models.IntegerField(null=True)),
                ('receipt_type', models.IntegerField(choices=[(1, 'fuel'), (2, 'meal'), (3, 'emergency'), (4, 'other')])),
                ('amount', models.IntegerField(default=0)),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.CargoManifest')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('business_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Business')),
                ('created_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.BusinessOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(max_length=7, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdapp.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField(max_length=7, null=True)),
                ('stop_type', models.IntegerField(choices=[(1, 'fuel'), (2, 'meal'), (3, 'restroom'), (4, 'lodging'), (5, 'accident'), (6, 'other')], null=True)),
                ('stop_location', models.CharField(max_length=100, null=True)),
                ('time_stop', models.DateTimeField(auto_now_add=True, null=True)),
                ('departed', models.DateTimeField(null=True)),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.CargoManifest')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('location_start', models.CharField(max_length=100)),
                ('location_end', models.CharField(max_length=100)),
                ('beginningOdometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endingOdometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trailer_number', models.IntegerField(null=True)),
                ('total_miles_traveled', models.DecimalField(decimal_places=1, max_digits=4)),
                ('average_price_per_gallon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gallons_of_gas_used', models.IntegerField(null=True)),
                ('number_of_unscheduled', models.IntegerField(null=True)),
                ('beginnning_weather_conditions', models.IntegerField(choices=[(1, 'normal'), (2, 'cloudy'), (3, 'rain'), (4, 'snow'), (5, 'hazardous'), (6, 'extremly hazardous')], default=1)),
                ('midway_weather_conditions', models.IntegerField(choices=[(1, 'normal'), (2, 'cloudy'), (3, 'rain'), (4, 'snow'), (5, 'hazardous'), (6, 'extremly hazardous')], default=1)),
                ('ending_weather_conditions', models.IntegerField(choices=[(1, 'normal'), (2, 'cloudy'), (3, 'rain'), (4, 'snow'), (5, 'hazardous'), (6, 'extremly hazardous')], default=1)),
                ('fuel_card_usage', models.IntegerField(choices=[('Yes', 'yes'), ('No', 'no')], default='Yes')),
                ('other_details', models.TextField(null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.CargoManifest')),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.CargoManifest')),
                ('manifest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.CargoManifest')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.CargoManifest')),
                ('order_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.CargoManifest')),
                ('order_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.CargoManifest')),
                ('trip_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.CargoManifest')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='location',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_id',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='category',
            field=models.IntegerField(choices=[(1, 'fuel'), (2, 'manfacturer'), (3, 'tech'), (4, 'retail'), (5, 'perishable'), (6, 'state_military_federal'), (7, 'other')], null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='state_of_matter',
            field=models.IntegerField(choices=[(1, 'liquid'), (2, 'solid'), (3, 'gas'), (4, 'plasma')], null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargo',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='business_net_worth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='business_phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='other_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='time_closed',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='time_open',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Company'),
        ),
        migrations.AddField(
            model_name='driver',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Company'),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='highest_trucking_license',
            field=models.IntegerField(choices=[('A', 'class a'), ('B', 'class b'), ('C', 'class c')], null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='other_certificate',
            field=models.IntegerField(choices=[('A', 'class a'), ('B', 'class b'), ('C', 'class c')], null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='sex',
            field=models.IntegerField(choices=[('M', 'male'), ('F', 'female')], null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ssn',
            field=models.CharField(db_index=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='trip_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='wage_plan',
            field=models.IntegerField(choices=[(1, 'hourly'), (2, 'miles')], null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='short_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_logo_'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.AddField(
            model_name='record',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdapp.Driver'),
        ),
        migrations.AddField(
            model_name='record',
            name='manifest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdapp.CargoManifest'),
        ),
        migrations.AddField(
            model_name='record',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdapp.Trip'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Driver'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Driver'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='driverexpenses',
            name='stop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Stop'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Driver'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Driver'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='point_of_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='cargo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Cargo'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Company'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wdapp.Business'),
        ),
    ]
