# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0002_auto_20181204_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessorder',
            name='MISC',
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.IntegerField(choices=[(1, 'fuel'), (2, 'nondurable manfacturer'), (3, 'tech'), (4, 'retail'), (5, 'wholesale trade'), (6, 'state_military_federal'), (7, 'other')], null=True),
        ),
        migrations.AlterField(
            model_name='businessorder',
            name='business_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businessorders', to='wdapp.Business'),
        ),
        migrations.AlterField(
            model_name='businessorder',
            name='hazmat_class',
            field=models.IntegerField(choices=[(1, 'Non-hazard'), (2, 'Explosive'), (3, 'Gases'), (4, 'Flammable Liquid'), (5, 'Combustible Liquid'), (6, 'Flammable Solid'), (7, 'Spontanaeously Combustible'), (8, 'Dangerous When Wet'), (10, 'Oxidizer and Organic Peroxide'), (11, 'Poison (Toxic) and Poison Inhalation Hazard'), (12, 'Radioactive'), (0, 'Miscellaneous, and the general Dangerous placard')], null=True),
        ),
        migrations.AlterField(
            model_name='businessorder',
            name='order_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
